export {
  CrucibleClient,
  CrucibleSession,
  engineOf,
  readAlignment,
  readAudioResult,
  readImageResult,
  readRenderResult,
  readSegmentResult,
  readVideoResult,
} from './client.js';
export type {
  CrucibleClientOptions,
  EventsOptions,
  WriteArtifactsOptions,
} from './client.js';

export { fleetSession } from './fleet.js';
export type {
  FleetDropout,
  FleetPlace,
  FleetQueueUpdate,
  FleetSessionOptions,
  FleetSessionResult,
} from './fleet.js';

export {
  ACCELERATOR_UNREADABLE,
  CAPABILITY_ROUTE_MISSING,
  CAPABILITY_ROUTE_UNKNOWN,
  CAPABILITY_UNDECIDED,
  CrucibleAcceleratorUnreadable,
  CrucibleAuthError,
  CrucibleBusy,
  CrucibleCapabilityUndecided,
  CrucibleCardHeld,
  CrucibleConfigError,
  CrucibleError,
  CrucibleFleetUnavailable,
  CrucibleNotACrucible,
  CruciblePairingError,
  CruciblePairingFileError,
  CrucibleProtocolError,
  CrucibleRefused,
  CrucibleServerError,
  CrucibleSessionClosed,
  CrucibleSessionHeld,
  CrucibleUnreachable,
  CrucibleVersionError,
  FLEET_UNAVAILABLE,
  INVALID_PAIRING,
  PAIRING_FILE_MALFORMED,
  ROUTE_BAD_MODEL,
  ROUTE_NOT_ROUTABLE,
  ROUTE_UPSTREAM_UNCONFIGURED,
  SERVER_BUSY,
  SESSION_CLOSED,
  SESSION_NOT_OPEN,
  SESSION_NOT_YOURS,
  SESSION_OPEN,
  SUBJECT_IN_USE,
  SUBJECT_NOT_INSTALLED,
  SUBJECT_REMOVE_FAILED,
  SUBJECT_UNKNOWN,
  UNKNOWN_QUEUE_SESSION,
  UNKNOWN_UPSTREAM,
  UPSTREAM_BAD_FIELD,
  UPSTREAM_IN_USE,
  UPSTREAM_NEVER_RESIDENT,
  UPSTREAM_RATE_LIMITED,
  UPSTREAM_REJECTED,
  UPSTREAM_TEST_REFUSALS,
  UPSTREAM_UNCONFIGURED,
  UPSTREAM_UNREACHABLE,
  VOICES_NEEDS_REFERENCE_MISSING,
  VOICES_NEEDS_REFERENCE_UNKNOWN,
  isServerSpecificRefusal,
} from './errors.js';
export type { FleetServerReason } from './errors.js';

export { PAIRING_SCHEME, parsePairing } from './pairing.js';
export type { Pairing } from './pairing.js';

export {
  CRUCIBLE_HOME_ENV,
  PAIRING_FILE,
  WINDOWS_HOME_DIRNAME,
  cruciblePairingPath,
  readPairingFile,
} from './pairing-file.js';

export {
  isStreamAudio,
  isStreamDone,
  isStreamRestart,
  isStreamRowError,
  openTtsStream,
} from './stream.js';
export type {
  CancelOutcome,
  StreamAudio,
  StreamEvent,
  StreamOptions,
  StreamRestart,
  StreamRowDone,
  StreamRowError,
  StreamTransport,
  StreamUnknown,
  TtsStreamSession,
} from './stream.js';

export {
  API_VERSION,
  TASK_TERMINAL_STATES,
  TERMINAL_EVENTS,
  isLlmCapability,
  isTaskBytesProgress,
  isTaskLineProgress,
  isTtsCapability,
} from './types.js';
export type {
  AcceleratorGpu,
  Activity,
  ActivityChat,
  ActivityJob,
  ActivitySlot,
  ActivityStreaming,
  AcceleratorHolder,
  AcceleratorResident,
  AcceleratorState,
  ArtifactData,
  ArtifactWrite,
  AlignItem,
  ArtifactHold,
  Alignment,
  AlignOptions,
  ImageOptions,
  ImageResult,
  AudioOptions,
  AudioResult,
  SegmentOptions,
  SegmentPoint,
  SegmentResult,
  VideoOptions,
  VideoResult,
  AlignWindow,
  AlignWindowResult,
  AsrOptions,
  CancelResult,
  CancelledData,
  Capability,
  CapabilityRecord,
  CapabilityRow,
  CapabilitySizing,
  CapabilityWork,
  ContextCeiling,
  CatalogRow,
  CrucibleModule,
  ChatMessage,
  ChatOptions,
  ChatResponse,
  ChatUsage,
  ChunkData,
  PauseCut,
  UnreadableRow,
  DecideAnswer,
  DecideAnswerCommon,
  DecideCallTiming,
  DecideChoiceAnswer,
  DecideChoiceQuestion,
  DecideItem,
  DecideItemsRequest,
  DecideItemsResponse,
  DecideMissing,
  DecideOptions,
  DecideQuestion,
  DecideRequest,
  DecideResponse,
  DecideScoreAnswer,
  DecideScoreQuestion,
  DecideTiming,
  DecideYesNoAnswer,
  DecideYesNoQuestion,
  DoneData,
  EstimateBasis,
  FailedData,
  GpuInfo,
  Health,
  EngineTaskRequest,
  InstallTaskRequest,
  JobCapability,
  JobEvent,
  JobFailure,
  JobInput,
  JobRequest,
  JobState,
  JobStatus,
  LlmCapability,
  LoadModelOptions,
  LoadVoiceOptions,
  CrucibleRole,
  EngineOwner,
  EngineRef,
  EngineRestartTaskRequest,
  ManagedBy,
  ModelDescriptor,
  ModelInfo,
  ModuleTaskRequest,
  PageRequest,
  PagesEngine,
  Ping,
  PullTaskRequest,
  ProgressData,
  Provenance,
  QueuedData,
  QueueChoice,
  QueueEvent,
  QueueItem,
  QueueWaitingFor,
  QueueList,
  QueuePosition,
  QueueRemoved,
  QueueSessionEnd,
  QueueSessionReason,
  QueueSessionState,
  QueueSessionStatus,
  SessionOptions,
  ServerEvent,
  ServerEventTopic,
  ServerEventsOptions,
  ServerSnapshot,
  ServerOverflow,
  ServerStopping,
  JobChangeEvent,
  JobProgressEvent,
  QueueChangeEvent,
  SessionChangeEvent,
  CardEvent,
  ChatInFlightEvent,
  TaskChangeEvent,
  TaskStepEvent,
  TaskProgressEvent,
  SettingsWrittenEvent,
  UnknownServerEvent,
  RemovalReason,
  RemovedData,
  StartedData,
  RenderChunk,
  RenderFailure,
  RenderOptions,
  RenderResult,
  Resumable,
  ResumableDiscarded,
  ResponseFormat,
  RouteSetting,
  ServerInfo,
  ServerSetup,
  LocalModelChoice,
  SettingsDocument,
  SettingsPatch,
  Stopping,
  SubjectKind,
  TaskBytesProgress,
  TaskCancelResult,
  TaskEvent,
  TaskLineProgress,
  TaskProgressData,
  TaskRequest,
  TaskSkippedData,
  TaskState,
  TaskStatus,
  UnmetNeed,
  TaskStepData,
  TerminalEventName,
  TtsCapability,
  UploadResult,
  UpstreamName,
  UpstreamSetting,
  UpstreamTestResult,
  VoiceChunkGap,
  VoiceEdgeFade,
  VoiceInfo,
  VoiceKind,
  VoicePace,
  VoiceSampling,
  VoiceServing,
  VoiceReference,
  InstallingDetails,
  WarmingData,
  WrittenArtifact,
} from './types.js';

export { SDK_VERSION } from './version.js';
export { startPairing, pollPairing, crucibleAddress, DEFAULT_CRUCIBLE_PORT, CrucibleConnectionError } from './connect.js';
export type { PairingRequest, PairingResult, PairingOptions, PendingPairing } from './connect.js';
