[model]
id = "qwen3-aligner"
family = "qwen3-forced-aligner"
parameters_m = 600

[backends.cuda-linux]
engine = "qwen3-forced-aligner"
hf_repo = "Qwen/Qwen3-ForcedAligner-0.6B"
revision = "c7cbfc2048c462b0d63a45797104fc9db3ad62b7"

dtype = "bfloat16"

memory_bytes_estimate = 5905580032

[backends.mlx-darwin]
engine = "qwen3-forced-aligner"
hf_repo = "Qwen/Qwen3-ForcedAligner-0.6B"
revision = "c7cbfc2048c462b0d63a45797104fc9db3ad62b7"

dtype = "bfloat16"

memory_bytes_estimate = 5885296640
