VERSION = "1.0.51"

from .protocol import API_HEADER, API_VERSION, CLIENT_HEADER

CLIENT_NAME_HEADER = CLIENT_HEADER

KEEP_ALIVE_SECONDS = 75

__all__ = ["VERSION", "API_VERSION", "API_HEADER", "CLIENT_NAME_HEADER",
           "KEEP_ALIVE_SECONDS"]
