VERSION = "1.0.51"
API_VERSION = 1
API_HEADER = "X-Crucible-Api"
CLIENT_NAME_HEADER = "X-Crucible-Client"

KEEP_ALIVE_SECONDS = 75

__all__ = ["VERSION", "API_VERSION", "API_HEADER", "CLIENT_NAME_HEADER",
           "KEEP_ALIVE_SECONDS"]
